

title: Seokcceeding
email: ehd0309@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  seok study memo
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://pds0309.github.io" 
github_username: pds0309
highlighter: rouge
svg:
  optimize: true
# Build settings

highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num"
category_dir: category/
tag_dir: tag/
my_list: [study , doit , else]


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
